controller_manager:
  ros__parameters:
    update_rate: 225  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gpio_controller:
      type: viprohead5_viscotec_ros2/GPIOController



gpio_command_controller:
  ros__parameters:
    gpios:
      - extruder
    command_interfaces:
      extruder:
        - enable
        - reset
        - velocity
