controller_manager:
  ros__parameters:
    update_rate: 225  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    extruder_trajectory_flow_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gpio_command_controller:
      type: gpio_controllers/GpioCommandController

velocity_controller:
  ros__parameters:
    joints:
      - extruder

extruder_trajectory_flow_controller:
  ros__parameters:
    joints:
      - extruder

    command_interfaces:
      - velocity

    state_interfaces:
      - velocity

    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

gpio_command_controller:
  ros__parameters:
    gpios:
      - extruder
    command_interfaces:
      extruder:
        - enable
        - reset
        - velocity
