controller_manager:
  ros__parameters:
    update_rate: 225  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


    extruder_stepper_velocity_controller:
      type: extruder_stepper_velocity_controller/ExtruderStepperVelocityController

    gpio_command_controller:
      type: gpio_controllers/GpioCommandController


extruder_stepper_velocity_controller:
  ros__parameters:
    joints:
      - extruder

gpio_command_controller:
  ros__parameters:
    gpios:
      - extruder
    command_interfaces:
      extruder:
        - enable
        - reset
        - velocity